### ISSUE TITLE
[Package - General] The structure

### ISSUE THREAD

**Issue by SimonMolinsky** [hs3city/ordinal-scale-stats-py#12]
We should invest some time to decide which Python module structure we will follow when we build the package.

We have two options:

1. `src` layout
2. flat layout

Both are described here (short): [src layout vs flat layout](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/)

Pros and cons of both in detail: [Python Package Structure for Scientific Python Projects](https://www.pyopensci.org/python-package-guide/package-structure-code/python-package-structure.html) 

I've used the flat layout every time. Why? Because almost all scientific Python packages use it ;) The src layout is more common in business environments. I'd choose the src layout this time, but what do you think about it? Do you know any issues we may encounter using the src layout?

**Comment by fgrabowski** [comment]
I dont think we can meet any issues using src layout however I think python packages mostly use flat structure approach.

**Comment by PawelKinczyk** [comment]
@SimonMolinsky as you mentioned. I think flat structure is better because we will have a lot examples from other packages (for me it will be very helpful)

**Comment by fgrabowski** [comment]
### Decision
After a few discussions we decided to move towards src package architecture - easier tests run, and more popular approach.
