### ISSUE TITLE
[Feature] Function to calculate Allison-Foster Index

### ISSUE THREAD

**Issue by SimonMolinsky** [hs3city/ordinal-scale-stats-py#14]
The Allison-Foster is a polarization measure within **a single group** defined as:

$$s(x; c) = \mu_{H}(x; c) - \mu_{L}(x; c)$$

where:
- $s(x; c)$ - Allison-Foster index,
- $\mu_{H}(x; c)$ - mean of the values **above** (H) group median value,
- $\mu_{L}(x; c)$ - mean of the values **below** (L) group median value.

Implement is a function that takes list-like objects with responses within a group. The function should return three elements:
- Allison-Foster index,
- $\mu_{H}(x; c)$
- $\mu_{L}(x; c)$.

Write docstring in a `numpy-doc` style: https://numpydoc.readthedocs.io/en/latest/format.html#sections

Write a simple functional test for the function using sample data.

Steps:
1. (Optional) Read paper: Allison RA, Foster JE. Measuring health inequality using qualitative data. J Health Econ. 2004 May;23(3):505-24. doi: 10.1016/j.jhealeco.2003.10.006. PMID: 15120468. **Especially page 514**.
2. Define a function as a Python script (it could now be a stand-alone script).
3. Write docstring.
4. Write a functional test (it could be the code that was used for function development).

**Comment by Reckony** [comment]
PR https://github.com/hs3city/ordinal-scale-stats-py/pull/20
