### ISSUE TITLE
Define function which calculates summary statistics of a set of observations

### ISSUE THREAD

**Issue by SimonMolinsky** [hs3city/ordinal-scale-stats-py#27]
The function should create summary statistics of a set of observations.

**Name**:

- It's a proposition, but maybe `ord_info()`?

**Parameters**:
- `ds`: *Iterable* - list-like or array-like object with categorical (ordinal) responses,
- `indicators`: set-like (values must be unique! - perform the uniqueness test), values must be ordered if not integers.

**Returns**:
- `statistics`: *pandas DataFrame*. DataFrame with columns:
  - `indicator` - with the name/value of an indicator,
  - `frequency` - with the count of how many times a response occurred,
  - `percent` - `frequency` divided by the number of responses,
  - `cumulative` - a sum of `percent`, from the lowest indicator to the highest. The last `cumulative` value must equal 100 (see example below).
  
**Process**:

1. Calculate frequency. You may use the function `numpy.unique()` with `return_counts=True` or `pandas.value_counts()` to get the frequency of unique indicators.
2. Calculate percent.
3. Sort order categories using `indicators` given by the user. If some indicator has a 0 count, set 0 as its frequency and percent.
4. Calculate cumulative percent going from the lowest indicator up.
5. Create DataFrame:
  - `index`: `indicators`
  - `index.name == "indicators"`
  - `columns`: `["frequency", "percent", "cumulative"]`
  - `data`: set per column.
The good idea is to create an empty DataFrame with an index only, then assign each column alone using your previous calculations. But you may decide to do it differently (for example, if you have used lists of dicts, you may create DataFrame directly).

**Example output**:

| indicators    | frequency | percent | cumulative |
|---------------|-----------|---------|------------|
| not satisfied | 5         | 10      | 10         |
| ok            | 10        | 20      | 30         |
| excellent     | 35        | 70      | 100        |

**Comment by devparikh360** [comment]
I would be glad to work on the feature you've added above. Kindly assign me

**Comment by SimonMolinsky** [comment]
@devparikh360 Thanks for the interest, but the function is assigned :) Maybe you would be interested in this issue #28 ?
