### ISSUE TITLE
Create summary statistics

### ISSUE THREAD

**Issue by SimonMolinsky** [hs3city/ordinal-scale-stats-py#28]
Create a function that calculates summary statistics of observed levels.

**Name**:

- `summary()`

**Parameters**:

- `ds`: *Iterable* - list-like or array-like object with categorical (ordinal) responses,

**Returns**:

- `summary_statistics`: *pandas DataFrame* with statistics.

**Process**:

- use https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html to get core statistics and return it
- you might be forced to change the input `ds` into `pandas Series` to use the method above.

**Comment by Reckony** [comment]
https://github.com/hs3city/ordinal-scale-stats-py/pull/30
