### ISSUE TITLE
Apouey index - iteration 1

### ISSUE THREAD

**Issue by SimonMolinsky** [hs3city/ordinal-scale-stats-py#33]
(This iteration assumes the index initialization with a look-up table with $\alpha$ parameter. In the next iteration, the function estimating $\alpha$ will be defined, and the output's confidence interval will be calculated).

# Definition

The index definition:

$$P_{2}(F) = 1 - \frac{2^{\alpha}}{C-1} \sum_{c=1}^{C-1}|F_{c}-\frac{1}{2}|^{\alpha}$$

where:

- $P_{2}(F)$ - index value based on the cumulative proportions of c-th category,
- $C$ - number of categories (we force users to use [3, 10] categories; see look-up table below),
- $F(c)$ = $\sum_{i=1}^{c} p_{i}$ - sum of proportions $p$ up to the c-th category,
- $p=(p_{1}, ..., p_{c-1}, p_{c})$ = $p_{c}$ - proportion for c-th category.

## Look-up table for the $\alpha$ parameter

| Number of categories  | $\alpha$                      |
| ----------------------------- | ------------------------------ |
| 3                                  | $=\frac{ln2}{ln3}$         |
| 4                                  | $=\frac{ln4 - ln3}{ln2}$ |
| 5                                  | $\approx 0.73$             |
| 6                                  | $\approx 0.66$             |
| 7                                  | $\approx 0.78$             |
| 8                                  | $\approx 0.75$             |
| 9                                  | $\approx 0.82$             |
| 10                                | $\approx 0.81$             |

# Example

We have a survey with ordered responses: `{very poor, poor, medium, well, very well}`. It is a 5-level grading. We get the following data:

| Category  | Category Level | Number of responses | Proportion |
| ------------- | -------------------- | ----------------------------- | ------------- |
| very poor | 1                       | 10                                | 0.2            |
| poor         | 2                       | 10                                | 0.2            |
| medium   | 3                       | 10                                | 0.2            |
| well          | 4                       | 5                                  | 0.1            |
| very well  | 5                       | 15                                | 0.3            |

We can calculate $F_{c}$ from the responses, up to the category $C-1$:

- $F_{1} = 0.2$
- $F_{2} = 0.4$
- $F_{3} = 0.6$
- $F_{4} = 0.7$

$\alpha$ is equal to **0.73** because we have 5 categories. Thus:

$$P_{2}(F) \approx 0.545$$

# Implementation aspects

- Please, [consider using the `info()` function](https://github.com/hs3city/ordinal-scale-stats-py/blob/main/src/core.py) to get the proportions of each category.
- For now, the look-up table should be hard coded into the script. An additional check of the number of categories is required, and if there are less than 3 or more than 10 categories the function should return `ValueError`.

# Bibliography

Apouey B. Measuring health polarization with self-assessed health data. Health Econ. 2007 Sep;16(9):875-94. doi: 10.1002/hec.1284. PMID: 17705333 - **PAGE 882 has the equation used in the package**.

**Comment by Reckony** [comment]
WIP https://github.com/hs3city/ordinal-scale-stats-py/pull/34
