### ISSUE TITLE
[Feature] `OrdinalScale` class

### ISSUE THREAD

**Issue by SimonMolinsky** [hs3city/ordinal-scale-stats-py#36]
Create class representing Ordinal Scale.

**name**: `OrdinalScale`

**init params**:
- `levels` (list-like) / example levels: `["basic", "medium", "hard"]`
- `orders` (optional, list-like, integers, every number must be non-zero and positive) / example orders: `[2, 4, 6]`

**attributes**:
- `levels` (the same as init param)
- `orders` - if `orders` parameter is not given then this attribute must be defined as `range` from `1` to `len(levels) + 1`.

**where?**

- in `src.core.py`

**Comment by imrannasrullah** [comment]
I'll take this

**Comment by imrannasrullah** [comment]
In the OrdinalScale class, which arguments are the and info funcitons supposed to take respectively to make them attributes to statistics and distribution respectively? Unless you mean setting these functions equal to class functions

**Comment by SimonMolinsky** [comment]
Hi @imrannasrullah 

I see what you meant! I am sorry for the confusion; using those functions is impossible. The class doesn't have access to the required data. Thus, I've redefined the first iteration, now it's extremely simple. It will grow with time; now we need a placeholder that stores information about ordinal scale ranges (in real-world settings, you could have a form with descriptive levels, as in the example).

**Comment by SimonMolinsky** [comment]
@imrannasrullah I've assigned you to this task. Please, create your own branch from the `main`, and when you are done, then push PR into `main`. The second thing, please, create boilerplate docs for this class following numpy style docs (https://github.com/hs3city/ordinal-scale-stats-py/blob/main/docs/dev-docstrings.md) - only parameters and attributes sections, don't bother with descriptions, I'll do it later.
