### ISSUE TITLE
Reformat `info()` function

### ISSUE THREAD

**Issue by SimonMolinsky** [hs3city/ordinal-scale-stats-py#39]
Reformat `info()` function: https://github.com/hs3city/ordinal-scale-stats-py/blob/5d90db3eede87c1d3831f0586ef649a7ab49d965/src/core.py#L10

- [x] Set `"cumulative"` column values as a ratio between 0 and 1 (instead of the 0-100 range). It is more convenient to have these values in the 0-1 interval for the computation of indexes,
- [x] Change `"ratio"` column name to `"ratio %"`

**Comment by SimonMolinsky** [comment]
Hi @Reckony

Just to be sure, have you worked on this issue? :)

**Comment by Reckony** [comment]
PR  https://github.com/hs3city/ordinal-scale-stats-py/pull/49
