### ISSUE TITLE
[main] Secure the branch

### ISSUE THREAD

**Issue by fgrabowski** [hs3city/ordinal-scale-stats-py#8]
###  **Secure main and dev branch** 

- [x] - pull request before merging to main has to be reviewed
- [x] - only users with admin permission are allowed to merge PRs

---
> Worth to note: We all are admins, but as far as I know this will be public in the future so those features are worth implementing soon to not forget.

**Comment by Reckony** [comment]
Marked tasks as done, closing the issue as rules are now applied.
